# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(max_length=120, validators=[restaurants.validators.validate_category]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(max_length=50, validators=[restaurants.validators.validate_district]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=120, validators=[restaurants.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
