# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=50)),
                ('popular_for', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
