# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import places.validators


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20180713_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, validators=[places.validators.validate_name]),
        ),
    ]
