# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import places.validators


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20180719_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(max_length=50, validators=[places.validators.validate_district]),
        ),
    ]
