# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('discription', models.TextField()),
            ],
        ),
    ]
