# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20180713_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
