# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-13 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20180713_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
