# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-15 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import hotels.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=100, validators=[hotels.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=150, validators=[hotels.validators.validate_name]),
        ),
    ]
