# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-15 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import hotels.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20180715_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=100, validators=[hotels.validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[hotels.validators.validate_district]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[hotels.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(validators=[hotels.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(validators=[hotels.validators.validate_star]),
        ),
    ]
