# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import transports.validators


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='capcity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(max_length=100, validators=[transports.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='transport',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle',
            field=models.CharField(max_length=50, validators=[transports.validators.validate_vehicle]),
        ),
    ]
